create extension if not exists "http" with schema "extensions";


create table "public"."Local_Test" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text
);


alter table "public"."Local_Test" enable row level security;

CREATE UNIQUE INDEX "Local_Test_pkey" ON public."Local_Test" USING btree (id);

alter table "public"."Local_Test" add constraint "Local_Test_pkey" PRIMARY KEY using index "Local_Test_pkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.talk_to_kanye()
 RETURNS text
 LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
DECLARE
    kanye_quote TEXT;
BEGIN
    SELECT content::json->>'quote' INTO kanye_quote
    FROM http_get('https://api.kanye.rest/');
    
    RETURN kanye_quote;
END;
$function$;

GRANT EXECUTE ON FUNCTION public.talk_to_kanye() TO PUBLIC;


grant delete on table "public"."Local_Test" to "anon";

grant insert on table "public"."Local_Test" to "anon";

grant references on table "public"."Local_Test" to "anon";

grant select on table "public"."Local_Test" to "anon";

grant trigger on table "public"."Local_Test" to "anon";

grant truncate on table "public"."Local_Test" to "anon";

grant update on table "public"."Local_Test" to "anon";

grant delete on table "public"."Local_Test" to "authenticated";

grant insert on table "public"."Local_Test" to "authenticated";

grant references on table "public"."Local_Test" to "authenticated";

grant select on table "public"."Local_Test" to "authenticated";

grant trigger on table "public"."Local_Test" to "authenticated";

grant truncate on table "public"."Local_Test" to "authenticated";

grant update on table "public"."Local_Test" to "authenticated";

grant delete on table "public"."Local_Test" to "service_role";

grant insert on table "public"."Local_Test" to "service_role";

grant references on table "public"."Local_Test" to "service_role";

grant select on table "public"."Local_Test" to "service_role";

grant trigger on table "public"."Local_Test" to "service_role";

grant truncate on table "public"."Local_Test" to "service_role";

grant update on table "public"."Local_Test" to "service_role";


